-- AUTO-GENERATED by scripts/generate-audit-triggers.ts (checked-in artifact).
-- Regenerate when new tenant-scoped tables are added.
-- Source: D-27, D-28, PITFALLS.md #6.
--
-- Chain semantics: row_hash = sha256(prev_hash || canonical_json(payload)).
-- Chain head is partitioned per (tenant_id, table_name) — SELECT ... FOR UPDATE
-- on audit_chain_state(tenant_id, table_name) is the only lock point.
-- Different (tenant,table) pairs DO NOT contend (Pitfall #6).

CREATE OR REPLACE FUNCTION gravel_audit_trigger() RETURNS trigger AS $fn$
DECLARE
  v_tenant_id UUID;
  v_table TEXT := TG_TABLE_NAME;
  v_row_pk TEXT;
  v_payload JSONB;
  v_prev_hash BYTEA;
  v_row_hash BYTEA;
  v_actor UUID;
  v_req UUID;
BEGIN
  v_tenant_id := COALESCE((NEW).tenant_id, (OLD).tenant_id);
  v_row_pk    := COALESCE((NEW).id::text, (OLD).id::text);

  BEGIN
    v_actor := NULLIF(current_setting('app.user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_actor := NULL; END;
  BEGIN
    v_req := NULLIF(current_setting('app.request_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_req := NULL; END;

  v_payload := jsonb_build_object(
    'action',  TG_OP,
    'table',   v_table,
    'row_pk',  v_row_pk,
    'before',  CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    'after',   CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );

  SELECT last_hash INTO v_prev_hash
    FROM audit_chain_state
   WHERE tenant_id = v_tenant_id AND table_name = v_table
   FOR UPDATE;

  IF v_prev_hash IS NULL THEN
    v_prev_hash := '\x00'::bytea;
    INSERT INTO audit_chain_state(tenant_id, table_name, last_hash)
      VALUES (v_tenant_id, v_table, v_prev_hash)
      ON CONFLICT (tenant_id, table_name) DO NOTHING;
  END IF;

  v_row_hash := digest(v_prev_hash || convert_to(v_payload::text, 'UTF8'), 'sha256');

  INSERT INTO audit_log(
    tenant_id, table_name, row_pk, action,
    before_jsonb, after_jsonb, actor_user_id, request_id,
    at_utc, prev_hash, row_hash
  ) VALUES (
    v_tenant_id, v_table, v_row_pk, TG_OP,
    v_payload->'before', v_payload->'after', v_actor, v_req,
    clock_timestamp(), v_prev_hash, v_row_hash
  );

  UPDATE audit_chain_state
     SET last_hash = v_row_hash
   WHERE tenant_id = v_tenant_id AND table_name = v_table;

  RETURN COALESCE(NEW, OLD);
END;
$fn$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach trigger to every tenant-scoped table.

DROP TRIGGER IF EXISTS audit_tenants ON tenants;
CREATE TRIGGER audit_tenants
  AFTER INSERT OR UPDATE OR DELETE ON tenants
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_countries ON countries;
CREATE TRIGGER audit_countries
  AFTER INSERT OR UPDATE OR DELETE ON countries
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_sites ON sites;
CREATE TRIGGER audit_sites
  AFTER INSERT OR UPDATE OR DELETE ON sites
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_production_zones ON production_zones;
CREATE TRIGGER audit_production_zones
  AFTER INSERT OR UPDATE OR DELETE ON production_zones
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_benches ON benches;
CREATE TRIGGER audit_benches
  AFTER INSERT OR UPDATE OR DELETE ON benches
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_permits ON permits;
CREATE TRIGGER audit_permits
  AFTER INSERT OR UPDATE OR DELETE ON permits
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_operational_days ON operational_days;
CREATE TRIGGER audit_operational_days
  AFTER INSERT OR UPDATE OR DELETE ON operational_days
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_shifts ON shifts;
CREATE TRIGGER audit_shifts
  AFTER INSERT OR UPDATE OR DELETE ON shifts
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();

DROP TRIGGER IF EXISTS audit_fx_rates ON fx_rates;
CREATE TRIGGER audit_fx_rates
  AFTER INSERT ON fx_rates
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();
