/**
 * Generator for per-table audit triggers (D-27, D-28).
 *
 * Reads `information_schema.columns` for tables with a `tenant_id` column,
 * emits one trigger function + trigger per table into a single .sql file.
 *
 * Chain semantics (PITFALLS.md #6):
 *   - One chain per (tenant_id, table_name).
 *   - Trigger SELECTs audit_chain_state FOR UPDATE — that row is the lock point.
 *   - Concurrent writers to DIFFERENT (tenant,table) pairs do NOT contend.
 *
 * Hash:
 *   row_hash = sha256(prev_hash || canonical_json(payload))
 *   payload  = jsonb_build_object('action',ACTION,'before',OLD,'after',NEW,
 *                                 'row_pk',row_pk,'at_utc',clock_timestamp())
 */
import * as fs from 'fs';
import * as path from 'path';
import type { DataSource } from 'typeorm';

export interface AuditTriggerSpec {
  tableName: string;
}

export async function listAuditableTables(ds: DataSource): Promise<AuditTriggerSpec[]> {
  const rows: Array<{ table_name: string }> = await ds.query(`
    SELECT DISTINCT table_name
    FROM information_schema.columns
    WHERE column_name = 'tenant_id'
      AND table_schema = 'public'
      AND table_name NOT IN ('audit_log', 'audit_chain_state')
    ORDER BY table_name
  `);
  return rows.map((r) => ({ tableName: r.table_name }));
}

export function buildTriggerSql(tables: AuditTriggerSpec[]): string {
  const header = `-- AUTO-GENERATED by scripts/generate-audit-triggers.ts.
-- Do NOT edit by hand. Regenerate via:
--   pnpm --filter @gravel/api migration:audit-gen
-- Source: D-27, D-28, PITFALLS.md #6.

CREATE OR REPLACE FUNCTION gravel_audit_trigger() RETURNS trigger AS $fn$
DECLARE
  v_tenant_id UUID;
  v_table TEXT := TG_TABLE_NAME;
  v_row_pk TEXT;
  v_payload JSONB;
  v_prev_hash BYTEA;
  v_row_hash BYTEA;
  v_actor UUID;
  v_req UUID;
BEGIN
  v_tenant_id := COALESCE((NEW).tenant_id, (OLD).tenant_id);
  v_row_pk    := COALESCE((NEW).id::text, (OLD).id::text);

  BEGIN
    v_actor := NULLIF(current_setting('app.user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_actor := NULL; END;
  BEGIN
    v_req := NULLIF(current_setting('app.request_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_req := NULL; END;

  v_payload := jsonb_build_object(
    'action',  TG_OP,
    'table',   v_table,
    'row_pk',  v_row_pk,
    'before',  CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    'after',   CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );

  -- Lock the per-(tenant,table) chain head. Different pairs do NOT contend.
  SELECT last_hash INTO v_prev_hash
    FROM audit_chain_state
   WHERE tenant_id = v_tenant_id AND table_name = v_table
   FOR UPDATE;

  IF v_prev_hash IS NULL THEN
    v_prev_hash := '\\x00'::bytea;
    INSERT INTO audit_chain_state(tenant_id, table_name, last_hash)
      VALUES (v_tenant_id, v_table, v_prev_hash)
      ON CONFLICT (tenant_id, table_name) DO NOTHING;
  END IF;

  v_row_hash := digest(v_prev_hash || convert_to(v_payload::text, 'UTF8'), 'sha256');

  INSERT INTO audit_log(
    tenant_id, table_name, row_pk, action,
    before_jsonb, after_jsonb, actor_user_id, request_id,
    at_utc, prev_hash, row_hash
  ) VALUES (
    v_tenant_id, v_table, v_row_pk, TG_OP,
    v_payload->'before', v_payload->'after', v_actor, v_req,
    clock_timestamp(), v_prev_hash, v_row_hash
  );

  UPDATE audit_chain_state
     SET last_hash = v_row_hash
   WHERE tenant_id = v_tenant_id AND table_name = v_table;

  RETURN COALESCE(NEW, OLD);
END;
$fn$ LANGUAGE plpgsql SECURITY DEFINER;

`;

  const triggers = tables
    .map(
      (t) => `DROP TRIGGER IF EXISTS audit_${t.tableName} ON ${t.tableName};
CREATE TRIGGER audit_${t.tableName}
  AFTER INSERT OR UPDATE OR DELETE ON ${t.tableName}
  FOR EACH ROW EXECUTE FUNCTION gravel_audit_trigger();
`,
    )
    .join('\n');

  return header + triggers;
}

export async function generateAndWrite(ds: DataSource, outPath: string): Promise<string[]> {
  const tables = await listAuditableTables(ds);
  if (tables.length < 7) {
    throw new Error(
      `Audit trigger generator found only ${tables.length} tenant-scoped tables; expected >=7. ` +
        `Verify migrations ran.`,
    );
  }
  fs.writeFileSync(outPath, buildTriggerSql(tables), 'utf8');
  return tables.map((t) => t.tableName);
}

// CLI mode (rarely used; the test container generates inline).
if (require.main === module) {
  const out = path.resolve(__dirname, '..', 'src', 'migrations', '1715500700000__generate_audit_triggers.sql');
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { AppDataSource } = require(path.resolve(__dirname, '..', 'ormconfig.ts'));
  AppDataSource.initialize()
    .then((ds: DataSource) => generateAndWrite(ds, out))
    .then((tables: string[]) => {
      // eslint-disable-next-line no-console
      console.log(`Wrote ${out} with ${tables.length} triggers: ${tables.join(', ')}`);
      process.exit(0);
    })
    .catch((e: unknown) => {
      // eslint-disable-next-line no-console
      console.error(e);
      process.exit(1);
    });
}
